### ISSUE TITLE
Text input does not affect to parsed value and input keyboard does not have decimal point in the ios.

### ISSUE THREAD

**Issue by SenBaatarkhuyag** [smofe/input_slider#3]
<img width="317" alt="Screen Shot 2022-10-03 at 8 57 51 pm" src="https://user-images.githubusercontent.com/107169337/193561300-17a13a5a-6766-4a68-9f27-3b311f0a872c.png">

**Comment by smofe** [comment]
This should be fixed with the newest version 0.3.1. 

Feel free to reopen if the issue remains.
